version = 0.1

[default.deploy.parameters]
stack_name = "cloud-resume-challenge"
resolve_s3 = true
s3_prefix = "cloud-resume-challenge"
region = "ap-south-1"
capabilities = "CAPABILITY_IAM"
image_repositories = []
signing_profiles = "GetFunction=\"anmolmadaik:251672427831\" PutFunction=\"anmolmadaik:251672427831\""

[default.global.parameters]
region = "ap-south-1"
