name: Deploy to sam

on:
  push:
    branches: [main]

jobs:
  build:

    permissions:
      id-token: write
      contents: read
      actions: read

    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v5

      - name: Generate SBOM
        uses: anchore/sbom-action@v0
        with:
          path: .


      - name: Set up Python
        uses: actions/setup-python@v5

      - name: Set up SAM
        uses: aws-actions/setup-sam@v2

      - name: Configure AWS credentials via OIDC
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{secrets.ROLE}}
          role-session-name: GitHubActions-Backend-${{ github.run_id }}
          aws-region: "ap-south-1"
      
      - name: Build SAM application
        run: sam build --use-container

        
      - name: Deploy SAM application
        run: sam deploy --debug
