name: Deploy to sam

on:
  push:
    branches: [main]

jobs:
  build:

    permissions:
      id-token: write
      contents: read
      actions: read

    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v5

      - name: Generate SBOM
        uses: anchore/sbom-action@v0
        with:
          path: .
          artifact-name: sbom.spdx.json
          format: spdx-json
          output-file: "${{ github.event.repository.name }}-sbom.spdx.json"

      - name: Upload SBOM artiact
        uses: actions/upload-artifact@v4
        with:
          name: sbom-spdx
          path: "${{ github.event.repository.name }}-sbom.spdx.json"
          retention-days: 90

      - name: Scan SBOM
        uses: anchore/scan-action@v7
        with:
          sbom: "${{ github.event.repository.name }}-sbom.spdx.json"
          fail-build: True
          severity-cutoff: critical
          output-format: json
          output-file: vuln_report.json

          
      - name: Upload Vulnerability Report
        uses: actions/upload-artifact@v4
        with:
          name: vuln_report
          path: vuln_report.json"
          retention-days: 90


      - name: Set up Python
        uses: actions/setup-python@v5

      - name: Set up SAM
        uses: aws-actions/setup-sam@v2

      - name: Configure AWS credentials via OIDC
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{secrets.ROLE}}
          role-session-name: GitHubActions-Backend-${{ github.run_id }}
          aws-region: "ap-south-1"
      
      - name: Build SAM application
        run: sam build --use-container

        
      - name: Deploy SAM application
        run: sam deploy --debug
